# Generated by Django 3.2 on 2025-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20231121_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abon_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='Абономент №')),
                ('abon_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Факультет')),
                ('all_number', models.IntegerField(blank=True, null=True, verbose_name='Жалпы фонд саны')),
                ('kyrgyz_num', models.IntegerField(blank=True, null=True, verbose_name='Кыргыз тилиндеги китептердин саны')),
                ('russ_num', models.IntegerField(blank=True, null=True, verbose_name='Орус тилиндеги китептердин саны')),
                ('inter_num', models.IntegerField(blank=True, null=True, verbose_name='Дуйнолук китептердин саны')),
                ('eng_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Англис тилиндеги китептер')),
                ('eng_num', models.IntegerField(blank=True, null=True, verbose_name='Англис тилиндеги китептердин саны')),
                ('ger_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Немец тилиндеги китептер')),
                ('ger_num', models.IntegerField(blank=True, null=True, verbose_name='Немец тилиндеги китептердин саны')),
                ('fra_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Француз тилиндеги китептер')),
                ('fra_num', models.IntegerField(blank=True, null=True, verbose_name='Француз тилиндеги китептердин саны')),
                ('tur_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Түрк тилиндеги китептер')),
                ('tur_num', models.IntegerField(blank=True, null=True, verbose_name='Түрк тилиндеги китептердин саны')),
                ('first_block', models.IntegerField(blank=True, null=True, verbose_name='1-блок')),
                ('second_block', models.IntegerField(blank=True, null=True, verbose_name='2-блок')),
                ('third_block', models.IntegerField(blank=True, null=True, verbose_name='3-блок')),
                ('teachers_work', models.IntegerField(blank=True, null=True, verbose_name='окутуучулардын эмгектери')),
            ],
            options={
                'verbose_name': 'Книжный фонд',
                'verbose_name_plural': 'Книжный фонд',
            },
        ),
    ]
