# Generated by Django 3.2 on 2025-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bookfond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfond',
            name='abon_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Абономент №'),
        ),
    ]
