# Generated by Django 3.2 on 2025-05-22 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_bookfond_abon_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.DeleteModel(
            name='Newspaper',
        ),
        migrations.AlterModelOptions(
            name='bookfond',
            options={'ordering': ('id',), 'verbose_name': 'Книжный фонд', 'verbose_name_plural': 'Книжный фонд'},
        ),
        migrations.AddField(
            model_name='news',
            name='social_website',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.news'),
        ),
    ]
