# Generated by Django 3.2 on 2025-05-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20250522_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsimage',
            old_name='image',
            new_name='images',
        ),
    ]
