# Generated by Django 3.2 on 2025-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_image_newsimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf', models.FileField(upload_to='catalog/pdfs/')),
            ],
            options={
                'verbose_name': 'Систематический каталог',
                'verbose_name_plural': 'Систематический каталог',
            },
        ),
    ]
