# Generated by Django 3.2 on 2025-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sistemcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField()),
                ('img', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Картинки')),
            ],
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='d_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='director_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='director_info_ky',
            new_name='info_ky',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='director_info_ru',
            new_name='info_ru',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='director',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='ibo',
            new_name='name_ky',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='e_res',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='e_res_img',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='e_res_info',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='e_res_info_ky',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='e_res_info_ru',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ibo_img',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ibo_info',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ibo_info_ky',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ibo_info_ru',
        ),
        migrations.AddField(
            model_name='structure',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
