# Generated by Django 3.2 on 2025-09-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20250612_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='bio_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='name_ky',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
