# Generated by Django 5.2.7 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20250903_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=100, verbose_name='слаг')),
                ('pdf', models.FileField(upload_to='jobo/pdfs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jobo/photos/')),
            ],
            options={
                'verbose_name': 'Жобо',
                'verbose_name_plural': 'Жобо',
                'ordering': ['-id'],
            },
        ),
    ]
