# Generated by Django 5.2.7 on 2026-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_jobo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobo',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='jobo',
            name='title',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
    ]
