# Generated by Django 3.2 on 2025-06-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forlibraries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
